package world

// A 13×7×13 room: basalt floor and ceiling, dark brick walls and five
// clear standing courses. The return slot stands in a worn-brick portal frame
// inside the room; its opening is air and its lintel does not obstruct a body.
// There is no physical hole in the chamber shell. The later portal system owns
// crossing the exit slot, just as it owns the arrival slot.
var instanceChamber = mustSchematic(
	[]Anchor{
		{X: 6, Y: 1, Z: 9, Kind: AnchorInstanceArrival},
		{X: 6, Y: 1, Z: 3, Kind: AnchorInstanceExit},
	},
	[]string{ // y=0
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
	},
	[]string{ // y=1
		"KKKKKKKKKKKKK",
		"K___________K",
		"K___________K",
		"K___k___k___K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"KKKKKKKKKKKKK",
	},
	[]string{ // y=2
		"KKKKKKKKKKKKK",
		"K___________K",
		"K___________K",
		"K___k___k___K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"KKKKKKKKKKKKK",
	},
	[]string{ // y=3
		"KKKKKKKKKKKKK",
		"K___________K",
		"K___________K",
		"K___k___k___K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"KKKKKKKKKKKKK",
	},
	[]string{ // y=4
		"KKKKKKKKKKKKK",
		"K___________K",
		"K___________K",
		"K___kkkkk___K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"KKKKKKKKKKKKK",
	},
	[]string{ // y=5
		"KKKKKKKKKKKKK",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"K___________K",
		"KKKKKKKKKKKKK",
	},
	[]string{ // y=6
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
		"bbbbbbbbbbbbb",
	},
)
