package world

// stableSchematic is 19×6×19. The timber stable occupies the back nine rows;
// its door opens into a paddock bounded by the stable, two cobble side walls and
// the front wall. The only opening to the outside is the three-block gate on +Z,
// preserving the facing convention shared by every settlement drawing.
//
// The paddock wall is a full block high because a schematic's palette already
// has cobblestone and this package must not add a fence block for one drawing.
var stableSchematic = mustSchematic(
	[]Anchor{
		{X: 5, Y: 0, Z: 4, Kind: AnchorStablemaster},
		{X: 4, Y: 0, Z: 13, Kind: AnchorPaddock},
		{X: 9, Y: 0, Z: 13, Kind: AnchorPaddock},
		{X: 14, Y: 0, Z: 13, Kind: AnchorPaddock},
	},
	[]string{ // y=0 — stable footing and the paddock's one-block wall
		"###################",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"########___########",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"#_________________#",
		"########___########",
	},
	[]string{ // y=1 — timber stable walls; the paddock stays open above its wall
		"PPPPPPPPPPPPPPPPPPP",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"PPPPPPPP___PPPPPPPP",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
	},
	[]string{ // y=2 — windows in both side walls and a lintel over the stable door
		"PPPPPPPPPPPPPPPPPPP",
		"P_________________P",
		"___________________",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"___________________",
		"P_________________P",
		"PPPPPPPPPPPPPPPPPPP",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
	},
	[]string{ // y=3 — the stable's closed upper wall
		"PPPPPPPPPPPPPPPPPPP",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"P_________________P",
		"PPPPPPPPPPPPPPPPPPP",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
	},
	[]string{ // y=4 — thatched eaves over the stable only
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTTTTTTT",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
	},
	[]string{ // y=5 — an inset roof cap
		"___________________",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"_TTTTTTTTTTTTTTTTT_",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
		"___________________",
	},
)
