package world

// RuinVariantCount bounds the caller's choice. No randomness lives in a drawing.
const RuinVariantCount = 2

// RuinFloorY is the hall's first air course above its floor, measured from the
// schematic's bottom. Place the bottom seven blocks below the desired hall level;
// the chamber has its own solid floor at y=0 and standing room from y=1.
const RuinFloorY = 7

// RuinSchematicFor returns a shared, read-only drawing. Invalid variants fall back
// to the first, matching SchematicFor's default rather than indexing unchecked.
func RuinSchematicFor(variant uint8) *Schematic {
	if variant == 1 {
		return brokenGableRuin
	}
	return brokenHallRuin
}

// centredRuinBuilding places the hall's standing level at floorY. Its sole stair
// descends six blocks to the enclosed chamber. The visitor writes explicit Air
// there; a future terrain caller must allow this excavation below the hall floor.
func centredRuinBuilding(variant uint8, plotX, plotZ, floorY int64, facing Facing) Building {
	return centreSchematic(BuildingRuin, variant, RuinSchematicFor(variant), plotX, plotZ,
		floorY-RuinFloorY, facing)
}

// Both original drawings occupy 15×19 columns, twelve courses high. Their only
// entrance faces +Z, at (7,7,17); the stair mouth (7,7,16) drops toward -Z to
// (7,1,10). The chamber occupies x=2..12, z=1..10 and y=0..5, enclosed by basalt
// walls, floor and ceiling except for that stair. There is no corridor beyond it.
//
// The arch stands centrally at z=5: smooth stone seals its five-wide opening,
// worn brick forms the jambs and lintel, and contrasting slate marks the runes.
// Its centre (7,2,5) deliberately names masonry, not an entity standing position.
//
// Upper walls stop at different courses, with collapsed masonry scattered across
// the open floor. Underscores clear the hall and broken wall tops; dots preserve
// the surrounding terrain. These are fixed layer literals, drafted from this plan
// and then reviewed as drawings; no runtime geometry or seed changes a schematic.

var brokenHallRuin = mustSchematic(
	[]Anchor{
		{X: 7, Y: 2, Z: 5, Kind: AnchorRuinArch},
		{X: 7, Y: 7, Z: 16, Kind: AnchorRuinStair},
	},
	[]string{ // y=0
		"...............",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=1
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kSSSSSk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=2
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_RSSSSSk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=3
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kSSSSSR_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=4
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kkkRkkk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=5
		"...............",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=6
		"...............",
		".kkbkkkbkkkbkk.",
		".kbkkkbkkkbkkk.",
		".bkkkbkkkbkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		".kbkkkbkkkbkkk.",
		".bkkkbkkkbkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		".kbkkk___kbkkk.",
		".bkkkb___bkkkb.",
		".kkkbk___kkkbk.",
		".kkbkk___kkbkk.",
		".kbkkk___kbkkk.",
		".bkkkb___bkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		"...............",
	},
	[]string{ // y=7
		"...............",
		".kKKk__kK_kKKk.",
		".K___________K.",
		".K_kk_________.",
		".k_k__________.",
		".K___________K.",
		".____________K.",
		".____________k.",
		".K_________k_K.",
		".K________kk_K.",
		".k___________k.",
		".K___________K.",
		".K___________K.",
		".__k__________.",
		".___k________K.",
		".K_________k_K.",
		".k___________k.",
		".KKkK_____KKkK.",
		"...............",
	},
	[]string{ // y=8
		"...............",
		".KKk_______Kk_.",
		".K____________.",
		".k_K__________.",
		".K____________.",
		"._____________.",
		".____________k.",
		".____________K.",
		".____________K.",
		".k___________k.",
		".K___________K.",
		".K___________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		".____________k.",
		".K___________K.",
		".KkKK________K.",
		"...............",
	},
	[]string{ // y=9
		"...............",
		".Kk___________.",
		".k____________.",
		".K____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".____________K.",
		".____________k.",
		".____________K.",
		".K___________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".____________K.",
		"._____________.",
		"...............",
	},
	[]string{ // y=10
		"...............",
		".k____________.",
		".K____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".____________K.",
		".____________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"...............",
	},
	[]string{ // y=11
		"...............",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"...............",
	},
)

var brokenGableRuin = mustSchematic(
	[]Anchor{
		{X: 7, Y: 2, Z: 5, Kind: AnchorRuinArch},
		{X: 7, Y: 7, Z: 16, Kind: AnchorRuinStair},
	},
	[]string{ // y=0
		"...............",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=1
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kSSSSSk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=2
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kSSSSSR_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=3
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_RSSSSSk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=4
		"...............",
		"..bbbbbbbbbbb..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_kkkRkkk_b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..b_________b..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=5
		"...............",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbbbbbbbbb..",
		"..bbbb___bbbb..",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....b___b.....",
		".....bbbbb.....",
		".....bbbbb.....",
		"...............",
		"...............",
	},
	[]string{ // y=6
		"...............",
		".kkbkkkbkkkbkk.",
		".kbkkkbkkkbkkk.",
		".bkkkbkkkbkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		".kbkkkbkkkbkkk.",
		".bkkkbkkkbkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		".kbkkk___kbkkk.",
		".bkkkb___bkkkb.",
		".kkkbk___kkkbk.",
		".kkbkk___kkbkk.",
		".kbkkk___kbkkk.",
		".bkkkb___bkkkb.",
		".kkkbkkkbkkkbk.",
		".kkbkkkbkkkbkk.",
		"...............",
	},
	[]string{ // y=7
		"...............",
		".kKKkKKkKK__Kk.",
		".K___________K.",
		".K_________k_K.",
		".k________kk_k.",
		".____________K.",
		"._____________.",
		".k____________.",
		".K_kk________K.",
		".K_k_________K.",
		".k____________.",
		".K____________.",
		".K_________k_K.",
		".k___________k.",
		".K___________K.",
		".__k_________K.",
		".k___________k.",
		".KKkK_____KKk_.",
		"...............",
	},
	[]string{ // y=8
		"...............",
		"._KkKKkKK____K.",
		".K___________K.",
		".k___________k.",
		".____________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		".K_K__________.",
		".k____________.",
		".K____________.",
		".K____________.",
		".k____________.",
		".K___________K.",
		".____________K.",
		".____________k.",
		"._____________.",
		"._kKK_________.",
		"...............",
	},
	[]string{ // y=9
		"...............",
		".__KKkKK_____K.",
		".____________k.",
		".____________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".K____________.",
		".K____________.",
		".k____________.",
		".K____________.",
		"._____________.",
		".____________k.",
		"._____________.",
		"._____________.",
		"._____________.",
		"...............",
	},
	[]string{ // y=10
		"...............",
		".___kKK_______.",
		".____________K.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".K____________.",
		".k____________.",
		".K____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"...............",
	},
	[]string{ // y=11
		"...............",
		".____K________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		".K____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"._____________.",
		"...............",
	},
)
